spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 30000ms
      
  # Cache Configuration for Production
  cache:
    type: redis
    redis:
      time-to-live: 7200000 # 2 hours in milliseconds for production
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "prod:ecommerce:"
      
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    
logging:
  level:
    in.ShopSphere.ecommerce: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
  file:
    name: /var/log/ecommerce/ecommerce.log
    max-size: 100MB
    max-history: 30
    
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
  
app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
    
server:
  port: ${PORT:8080}
  
# Production security settings
security:
  csrf:
    enabled: true
  rate-limit:
    enabled: true
    max-requests: 50
    window-size: 900
